### ISSUE TITLE
SharePoint Designer Level Permissions List

### ISSUE THREAD

**Issue by erikacrd** [Capital-Regional-District/EDRMS#133]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Get a list of users in the organization with designer-level access

#Outcome:
- [ ]  List of users specifying sites where they have designer-level permissions

**Comment by AndyCRD** [comment]
SharePoint Designer Permissions GotoCRDsite-2022-11-04.xlsx spreadsheet saved to EDRMS Project root folder:
Updated the spreadsheet with the definitions for Design and Limited access.
