### ISSUE TITLE
Identify Pre-Assessment Survey for Success Factors Metrics

### ISSUE THREAD

**Issue by lortrent** [Capital-Regional-District/EDRMS#148]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Identify metrics, questions to ne asked to capture baseline metrics to measure success.
Can we include anything about changing end user behaviors?
Things like saving to the desktop instead of SP.
Using the wrong document templates.  Opening an old doc and doing a Save As with an old template.
Ae there questions we can add to understand how people are using SharePoint?
Do you know where to store a document?

#Outcome:
- [ ]  01ProjectMgmt/Survey
- [ ] 
- [ ]

**Comment by zwei3011** [comment]
Closed per discussion on Mar 8, 2023's stand up meeting
