### ISSUE TITLE
Identify Usage Analysis Reporting Requirements (discovery tool)

### ISSUE THREAD

**Issue by erikacrd** [Capital-Regional-District/EDRMS#16]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

**#Description:**
Describe the analysis required for the current usage and identify the tool needed.

Notes:  

- This discovery tool needs to look at storage repositories to see what's there
- Current tool is [Treesize Professional ](url)

**#Outcome:**
- [ ]  Articulate the purpose for the tool and users that will need access
- [ ] Create a [request for IT to provision the analysis tool - on 02Tools folder under Project SP page

**Comment by AndyCRD** [comment]
Initial draft of requirements are captured in the EDRMS - Document Discovery Tool Requirements_AZ.xlsx in the 02Tools folder 
Meeting with Scott to identify other technical requirements scheduled for Nov 23.

**Comment by AndyCRD** [comment]
Scott has confirmed the last of the technical requirements.
The question of the tool scope relating to "Audit" has been raised - waiting for direction.
