### ISSUE TITLE
Discovery Tool Assessment

### ISSUE THREAD

**Issue by erikacrd** [Capital-Regional-District/EDRMS#20]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Work of going to vendor demos, shortlisting, and selecting a tool to discover the records footprint.

#Outcome:
- [ ]  Agreement on tool between IT and Records Management group
- [ ] Vendor documentation/demo materials to use as reference for RFP 
- [ ] Specify up front and yearly costs to aid decision making (IBC contains estimated budgets for this piece).
- [ ] Estimate stand-up time with brief rationale

**Comment by AndyCRD** [comment]
I've created an "evaluation spreadsheet" in the SharePoint site.  I have also begun the market scan for the tool.

**Comment by AndyCRD** [comment]
Having some trouble getting clarity on the scope.  What is meant by "Audit" in the IBC license item (“Software for data management, file classification, security permissions, ownership. Audit and tracking all changes over time.”).  Scott, Ken, Ryan, and I thought it meant security auditing and was out of scope, but review of many of the document discovery tools has uncovered a "compliance" component.  We need to know if this is in scope or out of scope for the document discovery tool.

In today's Weekly Wrap UP meeting, Zeb took on the responsibility to raise this to Lorna

**Comment by AndyCRD** [comment]
Evaluated Gimmal Discover tool with details in the evaluation spreadsheet in the SharePoint site.
